---
 - name: Import repo MongoDB
   shell: |
     echo "[mongodb-org-3.4]
     name=MongoDB Repository
     baseurl=https://repo.mongodb.org/yum/redhat/7/mongodb-org/3.4/x86_64/
     gpgcheck=1
     enabled=1
     gpgkey=https://www.mongodb.org/static/pgp/server-3.4.asc" > /etc/yum.repos.d/mongodb-org-3.4.repo
   when: ansible_os_family == "RedHat"
 - name: Install MongoDB Centos 7
   yum:
        name=mongodb-org state=present 
   when: ansible_os_family == "RedHat"
 - name: Install MongoDB Ubuntu 18.04
   apt:
        name=mongodb state=latest
   when: ansible_os_family == "Debian"