version: "3"

services:
    glpi:        
        build: .
        ports: 
            - "80:80"
        links: 
            - mysql:db
        env_file:
            - ./glpi.env
        volumes:
            - ../GLPI-Website:/var/www/html/glpi
    mysql:
        image: mariadb
        env_file:
            - ./glpi.env
        volumes:
            - ./mysql_data:/var/lib/mysql
