version: "3"

services:
    glpi:        
        build: .
        ports: 
            - "80:80"
        links: 
            - mysql:db
        env_file:
            - ./glpi.env
    mysql:
        image: mariadb
        env_file:
            - ./glpi.env