---
    - name: Import databases new
      postgresql_db:
        name: "{{ item }}"
        state: restore
        target: "{{ file_databases_new }}{{ item }}-{{lookup('pipe','date +%Y-%m-%d')}}.sql"
        login_host: "{{ host_old }}"
        login_user: "{{ user_old }}"
        login_password: "{{ passwd_old }}"
        port: '{{ port_dest | default("5432") }}'
      with_items: "{{ include_db }}"