---
    - name: Import Ubuntu
      shell: |
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
        sudo apt update
      when: ansible_os_family == "Debian"   
    - name: Import CentOS
      shell: |
        sudo yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        rpm -qi pgdg-redhat-repo
        sudo yum -y install epel-release yum-utils
        sudo yum-config-manager --enable pgdg12
      when: ansible_os_family == "RedHat"
    - name: Install PostgreSQL Ubuntu
      apt:
        name=postgresql-12 state=latest
        name=postgresql-client-12 state=latest
      when: ansible_os_family == "Debian"
    - name: Install PostgreSQL CentOS
      yum:
        name=postgresql12-server state=latest
        name=postgresql12 state=latest
      when: ansible_os_family == "RedHat"
    - name: Install python-psycopg2 on CentOS
      yum:
        name=python-psycopg2
        state=installed
      when: ansible_os_family == "RedHat"       
    - name: Install python-psycopg2 on Ubuntu
      apt:
        name=python-psycopg2
        state=latest
      when: ansible_os_family == "Debian"  