---
- name: Setup Monitoring Services
  hosts: localhost
  roles: 
  - name: Import Database PostgreSQL
    role: importdb
    folder_new: "/home/backup-PostgreSQL/"
    folder_old: "/home/backup-PostgreSQL-old/"
    host_db: 192.168.20.10
    user_db: postgres
    passwd_db: postgres
    port_db: 6432
    include_db:
        - partner