---
    - name: Import databases new
      postgresql_db:
        name: "{{ item }}"
        state: restore
        target: "{{ file_databases_new }}{{ item }}-{{lookup('pipe','date +%Y:%m:%d')}}.sql"
        login_host: "{{ host }}"
        login_user: "{{ user }}"
        login_password: "{{ passwd }}"
        port: '{{ port | default("5432") }}'
      with_items: "{{ include }}"