---
- name: Setup Monitoring Services
  hosts: localhost
  roles: 
  - name: Backup database Mysql
    role: backupdb
    folder_databases: "/home/backup-Mysql/"
    host_db: 192.168.20.3
    user_db: admin 
    passwd_db: admin
    port_db: 3306
    include_database:
        - hi