---
- name: Setup Monitoring Services
  hosts: localhost
  roles: 
  - name: Import Database MySQL
    role: importdb
    folder_new: "/home/backup-Mysql/"
    folder_old: "/home/backup-Mysql-old/"
    host_db: 192.168.20.3
    user_db: admin
    passwd_db: admin
    port_db: 3306
    include_db:
        - hyt