---
- name: Setup Monitoring Services
  hosts: localhost
  roles: 
  - name: Move Database PostgreSQL
    role: movedb
    folder_src: "/home/backup-Mysql/"
    host_src: 192.168.20.154
    user_src: admin 
    passwd_src: admin
    port_src: 3306
    include_database:
        - hy
    folder_dest: "/home/backup-Mysql-old/"
    host_dest: 192.168.20.3
    user_dest: admin
    passwd_dest: admin
    port_dest: 3306