---
- name: Create user PostgreSQL Full permission
  hosts: localhost
  roles:
  - name: Full permission user Mysql
    role: full.permission
    host_db: 192.168.40.45
    user_db: postgres
    pass_db: 1234@T
    user_need_create: user_full
    pass_need_create: 1234@T
    db_name:
        - chat  