---
- name: Create user PostgreSQL Readonly
  hosts: localhost
  roles:
  - name: Readonly user Mysql
    role: readonly
    host_db: 192.168.40.45
    user_db: postgres
    pass_db: 1234@T
    user_need_create: user_readonly
    pass_need_create: 1234@T
    db_name:
        - chat  