---
- name: Create user Mysql Readonly
  hosts: localhost
  roles: 
  - name: Readonly User Mysql
    role: readonly
    host_db: 192.168.40.45
    user_db: root
    pass_db: 1234@T
    user_need_create: user_readonly
    pass_need_create: 1234@T