---
- name: Setup Monitoring Services
  hosts: localhost
  roles: 
  - name: Dump Database Mysql
    role: movedb
    folder_src: "/home/backup-PostgreSQL/"
    host_src: "ahndaqw.rds.amazonaws.com"
    user_src: admin
    pass_src: admin
    port_src: 5432
    include_db_need_dump:
        - chat
    folder_dest: "/home/backup-PostgreSQL-old/"
    host_dest: 192.168.40.45
    user_dest: postgres
    pass_dest: 1234@T
    port_dest: 5432