- hosts: group1
  tasks:
  - name: Install Apache CentOS
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"
  - name: Start Apache CentOS
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
  - name: Install Apache Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"
  - name: Start Apache Ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"