version: '2'

services:
    # GLPI container
    glpi:
        build: .
        ports:
            - "80:80"
        links:
            - mysql:db
        env_file:
            - ./glpi.env
        volumes:
            - ../GLPI-Website:/var/www/html/glpi

    # Database container
    mysql:
        image: mariadb
        env_file:
            - ./glpi.env
        volumes:
            - ./mysql_data:/var/lib/mysql
